import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RecoilWrapper from "./helpers/RecoilWrapper/RecoilWrapper";
import { AuthProvider } from "./context/AuthContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TnNdshN music app",
  description: "Generated by 1919 dev team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <RecoilWrapper>
            {children}
          </RecoilWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
